In [1]:
from lib.dataeng import Etl

2024-01-26 18:46:25.804669: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
etl = Etl()

etl.repo

'/home/benjamin/Downloads/'

In [3]:
df = etl.extract_poids()

Le fichier poids le plus récent est : data_BEN_1706264904.zip, parmi :

data_BEN_1706083174.zip
data_BEN_1706264904.zip
data_BEN_1705987381.zip
data_BEN_1706158812.zip

In [4]:
df

,Date,Masse_Totale,Masse_Grasse,Masse_Osseuse,Masse_Musculaire,Masse_Hydrique,MG%,BMR
0,2024-01-26,73.83,12.46,3.07,58.29,41.34,0.168766,1695.592
1,2024-01-26,73.94,12.50,3.07,58.36,41.40,0.169056,1697.104
2,2024-01-26,73.90,12.50,3.07,58.32,41.35,0.169147,1696.240
3,2024-01-26,74.10,12.65,3.07,58.37,41.37,0.170715,1697.320
4,2024-01-26,73.76,12.35,3.07,58.32,41.38,0.167435,1696.456
...,...,...,...,...,...,...,...,...
8900,2020-08-14,104.50,33.85,NaN,NaN,NaN,0.323923,1896.040
8901,2020-08-13,104.40,34.34,NaN,NaN,NaN,0.328927,1883.296
8902,2020-08-12,104.35,33.80,NaN,NaN,NaN,0.323910,1893.880
8903,2020-08-11,104.65,33.15,NaN,NaN,NaN,0.316770,1914.400
8906,2020-08-09,107.25,37.19,NaN,NaN,NaN,0.346760,1883.296

In [5]:
df = etl.extract_food()

Le fichier food le plus récent est : File-Export-2020-08-03-to-2024-01-26.zip, parmi

File-Export-2020-08-03-to-2024-01-26.zip
File-Export-2020-08-03-to-2024-01-24.zip
File-Export-2020-08-03-to-2024-01-25.zip
File-Export-2020-08-03-to-2024-01-23.zip

In [6]:
df

            Date       Meal  Calories  Lipides  Glucides  Proteines
0     2020-08-03  Breakfast     621.4     27.9      69.7       22.4
1     2020-08-03     Dinner     581.6     20.4      84.5       17.1
2     2020-08-03      Lunch     656.0     41.4      26.6       33.5
3     2020-08-03     Snacks      58.0      0.0      14.0        0.0
4     2020-08-04  Breakfast    1111.6     49.0     137.8       34.3
...          ...        ...       ...      ...       ...        ...
3692  2024-01-24     Dinner     243.9      6.1      40.6        9.4
3693  2024-01-24      Lunch     694.3      9.7      79.1       75.8
3694  2024-01-25  Breakfast     742.7     14.9      59.4      102.4
3695  2024-01-25     Dinner     365.6      5.8      49.9       27.4
3696  2024-01-25      Lunch     695.0     16.4      54.7       85.0

[3697 rows x 6 columns]

In [7]:
df = etl.extract_exos()

Le fichier exercices le plus récent est : polar-user-data-export_12baa4ce-79a5-40f8-ad40-74308f7c2c26.zip, parmi :

polar-user-data-export_872b7f7c-c5e0-4b44-b031-f8e8821babae.zip
polar-user-data-export_12baa4ce-79a5-40f8-ad40-74308f7c2c26.zip

100%|██████████| 1828/1828 [01:20<00:00, 22.66it/s]

start date = 2021-03-29

In [8]:
df.tail(30)

            exo_duree           exo_type  exo_cals_bruts
exo_date
2023-12-27   6123.605  STRENGTH_TRAINING           581.0
2023-12-28      0.000                  0             0.0
2023-12-29   3180.584  STRENGTH_TRAINING           244.0
2023-12-30   1680.720            JOGGING           261.0
2023-12-31   6005.953  STRENGTH_TRAINING           671.0
2024-01-01      0.000                  0             0.0
2024-01-02      0.000                  0             0.0
2024-01-03   3128.453  STRENGTH_TRAINING           251.0
2024-01-04   1621.203      INDOOR_ROWING           245.0
2024-01-05   2220.597  STRENGTH_TRAINING           202.0
2024-01-06      0.000                  0             0.0
2024-01-07   3240.580  STRENGTH_TRAINING           291.0
2024-01-08   3180.000  STRENGTH_TRAINING           403.0
2024-01-09   2040.000  STRENGTH_TRAINING           195.0
2024-01-10   3600.000            WALKING           200.0
2024-01-11   3240.000  STRENGTH_TRAINING           258.0
2024-01-12   3120.000  STRENGTH_TRAINING           454.0
2024-01-13      0.000                  0             0.0
2024-01-14   2160.000  STRENGTH_TRAINING           187.0
2024-01-15   3360.000  STRENGTH_TRAINING           411.0
2024-01-16   3000.000  STRENGTH_TRAINING           454.0
2024-01-17   1920.000  STRENGTH_TRAINING           202.0
2024-01-18      0.000                  0             0.0
2024-01-19   3480.000  STRENGTH_TRAINING           399.0
2024-01-20   3240.000  STRENGTH_TRAINING           478.0
2024-01-21   1980.000      INDOOR_ROWING           336.0
2024-01-22   3180.000  STRENGTH_TRAINING           369.0
2024-01-23      0.000                  0             0.0
2024-01-24   3060.000  STRENGTH_TRAINING           433.0
2024-01-25   1320.000      INDOOR_ROWING           187.0